In [4]:
import pandas as pd
df = pd.read_csv('train_data.csv')
df.head(5)

,word_id,word,answer,participant_id,text
0,enc_wikimoon_13_page_1_0,Luna,0,28,enc_wikimoon
1,enc_wikimoon_13_page_1_1,https://ro.wikipedia.org/wiki/Luna,668,28,enc_wikimoon
2,enc_wikimoon_13_page_1_2,De,0,28,enc_wikimoon
3,enc_wikimoon_13_page_1_3,la,220,28,enc_wikimoon
4,enc_wikimoon_13_page_1_4,"Wikipedia,",0,28,enc_wikimoon

In [5]:
df['participant_id'].unique()

array([28, 44, 42, 29, 22, 43, 48, 17, 34, 38, 35, 39, 15, 30, 46, 49, 50,
       20, 27, 25, 31, 23, 32, 33, 14, 37, 21, 41, 26, 45])

In [7]:
df[df['participant_id']==44]

,word_id,word,answer,participant_id,text
4507,enc_wikimoon_13_page_1_0,Luna,0,44,enc_wikimoon
4508,enc_wikimoon_13_page_1_1,https://ro.wikipedia.org/wiki/Luna,1257,44,enc_wikimoon
4509,enc_wikimoon_13_page_1_2,De,0,44,enc_wikimoon
4510,enc_wikimoon_13_page_1_3,la,0,44,enc_wikimoon
4511,enc_wikimoon_13_page_1_4,"Wikipedia,",276,44,enc_wikimoon
...,...,...,...,...,...
9009,popsci_caveman_12_page_8_44,special,420,44,popsci_caveman
9010,popsci_caveman_12_page_8_45,în,0,44,popsci_caveman
9011,popsci_caveman_12_page_8_46,Suedia,680,44,popsci_caveman
9012,popsci_caveman_12_page_8_47,și,0,44,popsci_caveman
9013,popsci_caveman_12_page_8_48,Finlanda.,468,44,popsci_caveman