# TASK DESCRIPTION

**Legend:**

Young Alex has a beloved BERT model that he carries everywhere on his trusty flash drive. One day, during an excursion along the River Styx, a few drops of water landed on the precious device, corrupting the model's weights.

Heartbroken, Alex rushed home to fix the neural network. After quick analysis, he discovered only the token embeddings were damaged - the rest of the architecture (attention blocks and heads) remained perfectly intact. Now he needs to restore the model's performance on Sentiment Analysis Task.

**Task:**

You need to fix the broken vectors of the Embeddings matrix of the model so as to improve the quality of the model on the task of text sentiment analysis.

**Restrictions:**

- You can not use any other transformer based pre-trained models and LLMs.

- You can not any additional data

- You can not fine-tune or pre-train model

===

When you make a submit, make a Quick Save of the notebook, otherwise we may reject your solution.

You must solve this task on KAGGLE (YOU CAN'T USE CLOUD.RU)

==========

**Легенда:**

Young Alex имеет любимую модель BERT, которую он везде носит на своей надежной флешке. Однажды, во время экскурсии вдоль реки Стикс, несколько капель воды попало на драгоценное устройство, повредив веса модели.

С разбитым сердцем Алекс поспешил домой, чтобы починить нейронную сеть. После быстрого анализа он обнаружил, что повреждены только эмбеддинги токенов — остальная архитектура (блоки внимания и головы) осталась полностью нетронутой.

Теперь ему нужно восстановить производительность модели, оставив все остальные веса замороженными (никакие изменения в механизмах внимания или других компонентах не допускаются). Ваша задача — помочь Алексу достичь этой цели, не нарушив его ностальгическую привязанность к оригинальной модели.

**Задача:**

Вам необходимо починить сломанные вектора матрицы Embeddings модели так, чтобы улучшить качество модели на задаче анализа тональности текста.

**Ограничения:**

- Вы не можете использовать никакие другие предобученные модели на основе архитектуры Трансформер и LLM.

- Вы не можете использовать никакие дополнительные данные.

- Вы не можете дообучать или предобучать модель.

===

При отправке решения сделайте Quick Save ноутбука, иначе мы можем отклонить ваше решение.

Эту задачу необходимо решить на KAGGLE (ВЫ НЕ МОЖЕТЕ ИСПОЛЬЗОВАТЬ CLOUD.RU)

# DEPENDINGS

In [1]:
import numpy as np
import pandas as pd
import torch
np.random.seed(21)

# LOAD DATASET

In [2]:
val_data_path = "./neoai-2025-broken-bert/val_dataset.csv"
test_data_path = "./neoai-2025-broken-bert/test.csv"

temp_df = pd.read_csv(val_data_path)
test_df = pd.read_csv(test_data_path)
temp_df.head(5)

   id                                               text    labels
0   0  simple recipe for creamy spaghetti with bacon,...   neutral
1   1                                        wow heather   neutral
2   2  @Djalfy I sound really Brummie lol but most of...  negative
3   3  the fact my room is so hot is making me feel sick  negative
4   4                       just came back from the mall   neutral

In [3]:
len(temp_df)

2500

# LOAD TOKENIZER & MODEL

In [4]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("Ilseyar-kfu/broken_bert")

In [5]:
class Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

# MODEL CHANGES

In [6]:
model = AutoModelForSequenceClassification.from_pretrained("Ilseyar-kfu/broken_bert")

new_embedings = model.bert.embeddings.word_embeddings.weight.detach().numpy().copy()

# There's magic going on here!!! And we get very new !!! new_embedings !!!

model.bert.embeddings.word_embeddings.weight = torch.nn.Parameter(torch.Tensor(new_embedings))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [ ]:
# model = AutoModelForSequenceClassification.from_pretrained('fixed_bert/checkpoint-1278')

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [7]:
for param in model.parameters():
    param.requires_grad = False

model.bert.embeddings.word_embeddings.weight.requires_grad = True

trainable = [name for name, p in model.named_parameters() if p.requires_grad]
print(trainable)

['bert.embeddings.word_embeddings.weight']

# Training

In [8]:
from sklearn.model_selection import train_test_split
train_df, val_df = train_test_split(temp_df, test_size=0.1)

train_encodings = tokenizer(train_df['text'].to_list(), padding=True, truncation=True, max_length=256)
val_encodings = tokenizer(val_df["text"].to_list(), truncation=True, padding=True, max_length=256)

label2id = {'neutral': 0, 'positive': 1, 'negative': 2}
train_labels = [label2id[label] for label in train_df["labels"].to_list()]
val_labels = [label2id[label] for label in val_df["labels"].to_list()]

train_dataset = Dataset(train_encodings, train_labels)
val_dataset = Dataset(val_encodings, val_labels)

In [9]:
idx = 0
item = {key: torch.tensor(val[idx]) for key, val in val_encodings.items()}
item

{'input_ids': tensor([  101,  7570, 17417,  2078,  9457, 10733,  1010,  5474,  1998, 11565,
         10733,  1998, 21500, 10610,  2005,  4596,  2007,  9493,  1998, 12323,
          1012,  2204,  2335,   999,   102,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0]),
 'token_type_ids': tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0]),
 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0])}

In [10]:
texts_2_score = val_df["text"].to_list() + test_df["text"].to_list()

In [11]:
from transformers import TrainingArguments, Trainer

args = TrainingArguments(
    output_dir='./fixed_bert',
    num_train_epochs=10,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    learning_rate=5e-5,
    weight_decay=1e-3,
    eval_strategy='epoch',
    save_strategy='epoch',
    logging_strategy='epoch',
    load_best_model_at_end=True,
    metric_for_best_model='loss'
)

trainer = Trainer(model, args, train_dataset=train_dataset, eval_dataset=val_dataset)
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=710, training_loss=1.0124565984161806, metrics={'train_runtime': 146.011, 'train_samples_per_second': 154.098, 'train_steps_per_second': 4.863, 'total_flos': 774694291455000.0, 'train_loss': 1.0124565984161806, 'epoch': 10.0})

# EVALUATION

In [12]:
from sklearn.metrics import f1_score
from numpy import argmax
from transformers import pipeline
# import wandb
# wandb.init(mode= "disabled")

In [13]:
list(val_df["text"])[0]

'Hoisin duck pizza, salt and pepper pizza and gelato for dinner with Edmund and Jade. Good times!'

In [14]:
encoded = tokenizer(list(val_df["text"]), padding=True, truncation=True, max_length=256, return_tensors='pt')
encoded = {k: v.to(model.device) for k, v in encoded.items()}
model(**encoded)

SequenceClassifierOutput(loss=None, logits=tensor([[ 3.6433e-01,  3.1979e-01, -7.7919e-01],
        [ 2.9750e-01, -1.5605e+00,  1.0596e+00],
        [ 5.3907e-01, -1.1001e+00,  4.2352e-01],
        [ 1.8940e-01, -4.1646e-01,  3.4140e-02],
        [-4.6511e-01, -7.2381e-02,  2.4888e-01],
        [ 5.0164e-01, -1.7492e+00,  1.0233e+00],
        [ 8.0335e-01, -1.5787e+00,  4.0676e-01],
        [ 4.3528e-01, -2.3311e-01, -5.0398e-01],
        [-4.9168e-01,  1.9435e+00, -9.6223e-01],
        [ 3.3221e-01, -5.8943e-01, -8.1052e-02],
        [ 2.2743e-01, -2.1493e-01, -1.4060e-01],
        [ 3.0756e-01, -3.6447e-01, -9.5627e-02],
        [ 4.0378e-02,  5.9399e-01, -7.8203e-01],
        [-3.2303e-01, -2.1355e+00,  2.2309e+00],
        [-1.4996e-01,  3.3818e-01, -3.0370e-01],
        [ 1.0256e+00, -1.1072e+00, -3.0304e-01],
        [-2.7718e-02, -3.7555e-01,  2.8391e-01],
        [-2.5635e-01, -6.5043e-02,  3.9560e-02],
        [ 2.1815e-01,  1.5209e-01, -5.1547e-01],
        [ 2.3131e-01, -5.7656e-01,  1.6972e-01],
        [ 3.7285e-01, -2.6375e-01, -3.6936e-01],
        [ 4.1266e-01, -1.2812e+00,  6.2616e-01],
        [ 2.4876e-01, -5.7657e-01,  8.2111e-02],
        [ 1.5120e-01, -1.8162e+00,  1.3821e+00],
        [ 1.3385e-01, -1.3903e+00,  1.0318e+00],
        [ 5.8312e-01, -3.6704e-01, -2.7131e-01],
        [ 5.7938e-01, -7.5176e-01, -1.1513e-01],
        [ 4.4364e-01, -9.1440e-01,  2.1528e-01],
        [-1.6803e-02,  1.5672e-01, -2.7456e-01],
        [ 5.3880e-01, -2.2491e-01, -4.9178e-01],
        [ 2.2404e-01, -2.8385e-01, -7.8609e-02],
        [-1.9595e-01,  5.4528e-01, -4.7695e-01],
        [ 1.4613e+00, -1.6166e+00, -2.6853e-01],
        [-8.4364e-01,  1.6282e+00, -4.6933e-01],
        [-1.0503e-01, -2.4003e-01,  1.8364e-01],
        [ 1.7543e-01, -4.9361e-01,  1.5187e-01],
        [ 3.0441e-01, -4.4187e-01, -1.2386e-01],
        [-4.2870e-01,  3.0909e-01, -8.8915e-02],
        [ 4.1630e-01,  2.6648e-01, -9.0569e-01],
        [ 3.1939e-01,  4.4916e-01, -7.0885e-01],
        [ 2.5268e-01, -4.1685e-01, -1.7901e-02],
        [ 2.2926e-01, -4.3182e-01,  2.9102e-02],
        [ 8.5982e-01, -9.3958e-01, -2.2961e-01],
        [ 1.0596e-01, -2.5950e-01, -7.1193e-02],
        [-1.2518e-01,  6.1992e-01, -4.7845e-01],
        [ 8.4375e-03,  2.2458e-03, -6.7439e-02],
        [ 1.8623e-01, -4.0643e-01,  1.1978e-01],
        [-5.1778e-01,  1.7205e+00, -9.0894e-01],
        [ 4.1295e-01, -2.6045e-01, -3.2669e-01],
        [ 5.7812e-01, -9.1165e-01,  1.7796e-01],
        [-3.7156e-04,  5.3418e-01, -7.2114e-01],
        [ 5.9847e-01, -6.8032e-01, -3.6028e-01],
        [-3.6202e-01,  1.3031e+00, -7.1198e-01],
        [ 2.5287e-01, -3.3728e-01, -2.0281e-01],
        [-5.9173e-01, -2.1103e-01,  5.3337e-01],
        [ 3.5912e-02, -1.3182e-01, -1.1343e-01],
        [ 4.4723e-01, -1.6241e+00,  9.3624e-01],
        [-8.0481e-01,  2.0209e+00, -6.5114e-01],
        [ 1.8877e-01, -9.1379e-01,  5.7360e-01],
        [-5.3686e-02,  1.0157e+00, -8.7894e-01],
        [ 3.3922e-01, -1.7052e+00,  1.0368e+00],
        [-3.6417e-01,  1.4889e+00, -1.1331e+00],
        [ 2.2385e-02,  7.9832e-01, -8.8627e-01],
        [-1.5590e-01,  7.9534e-01, -6.2494e-01],
        [ 6.7054e-01, -3.0625e-01, -5.8883e-01],
        [ 2.8272e-01, -7.6945e-02, -3.6099e-01],
        [ 1.7345e-01, -3.6438e-01,  1.2850e-01],
        [ 5.0947e-01, -1.0419e+00,  2.1705e-01],
        [ 2.4770e-01, -3.6008e-01, -2.7627e-02],
        [ 4.5237e-01, -4.9858e-01, -3.2585e-01],
        [-3.4649e-02,  8.7788e-01, -9.0565e-01],
        [ 4.5990e-01, -8.3416e-01,  3.0276e-02],
        [ 2.7669e-01, -5.2502e-01,  2.5199e-02],
        [ 6.6444e-01, -3.9451e-01, -3.9296e-01],
        [ 1.7538e-01, -1.1950e+00,  7.6681e-01],
        [ 3.9823e-01, -1.0928e+00,  3.9422e-01],
        [-1.9367e-01,  1.1455e+00, -9.2436e-01],
        [ 8.1258e-02, -4.7221e-01,  2.3863e-01],
        [-1.2781e-01, -1.2793e-01,  8.3677e-02],
        [ 8.9877e-01, -1.6614e+00,  6.6868e-01],
        [-7.8569e-01,  7.5758e-01,  2.7689e-01],
        [ 3.4429e-01, -1.1545e-01, -4.6315e-01],
        [-4.3910e-01,  1.0873e+00, -5.2214e-01],
        [ 1.9654e-01, -4.5776e-01, -1.1612e-02],
        [ 9.9515e-03, -6.6551e-01,  5.1357e-01],
        [ 7.5942e-02, -1.4063e+00,  1.1804e+00],
        [ 5.0702e-01, -2.4037e-01, -4.9084e-01],
        [-4.3337e-02, -6.6718e-01,  5.7073e-01],
        [-5.1931e-02,  8.7711e-01, -8.7812e-01],
        [ 5.9075e-01, -1.4351e+00,  6.4006e-01],
        [ 1.6892e-01, -2.4633e-01, -1.3915e-01],
        [ 1.5832e-01, -5.9821e-01,  2.2212e-01],
        [-4.0411e-01,  1.2776e+00, -6.4243e-01],
        [ 3.1094e-01, -2.5656e-01, -2.0870e-01],
        [ 3.2848e-01, -1.3377e+00,  7.4739e-01],
        [-2.0203e-01,  5.1504e-02,  8.4048e-03],
        [ 1.6007e-01, -1.0444e+00,  6.3906e-01],
        [ 1.5398e-01,  4.4305e-01, -6.5008e-01],
        [-5.4069e-01,  1.0878e+00, -2.5147e-01],
        [-1.4582e-01, -9.9809e-01,  7.6855e-01],
        [-6.1254e-01,  1.4438e+00, -4.1279e-01],
        [ 4.7258e-01, -1.1860e+00,  5.0982e-01],
        [ 2.3437e-01,  3.2350e-01, -6.5595e-01],
        [-6.2729e-01,  1.7031e+00, -6.4782e-01],
        [ 8.7893e-02,  3.1269e-01, -4.8244e-01],
        [ 6.2965e-01, -1.0919e+00,  2.3123e-01],
        [ 1.2239e-01, -3.4509e-01,  8.0202e-02],
        [-3.7210e-01,  1.0632e+00, -4.2471e-01],
        [ 4.5670e-01, -8.0366e-01,  8.3147e-02],
        [ 5.0963e-01, -3.9197e-01, -2.9650e-01],
        [ 4.5657e-01, -9.2743e-01,  4.1116e-02],
        [ 1.5095e-01, -2.2579e+00,  2.1403e+00],
        [ 2.2657e-01, -1.8934e+00,  1.5803e+00],
        [-2.0936e-03,  2.5004e-01, -3.7083e-01],
        [-7.4526e-01,  1.9254e+00, -6.2560e-01],
        [ 3.3210e-01, -8.0460e-01,  3.0279e-01],
        [-7.3717e-01, -4.6001e-01,  1.0209e+00],
        [ 6.3327e-01, -1.8271e+00,  6.5816e-01],
        [ 4.4488e-01, -6.0455e-01,  2.5598e-02],
        [-4.7579e-01,  1.4336e+00, -6.6870e-01],
        [-1.8515e-01,  4.6107e-01, -4.5213e-01],
        [ 3.7889e-01, -2.2452e-01, -4.6253e-01],
        [-2.7301e-01,  8.2020e-02,  8.2381e-02],
        [-3.6914e-01,  1.5526e+00, -6.3304e-01],
        [ 2.1122e-01, -7.3232e-02, -3.6612e-01],
        [ 3.3418e-01, -5.1445e-01, -6.9811e-02],
        [ 4.3334e-01, -8.5908e-01,  1.9913e-01],
        [ 6.7239e-01, -8.8839e-01, -5.9244e-02],
        [-3.1356e-01,  1.0192e+00, -6.2893e-01],
        [ 8.9713e-01, -2.4186e-01, -9.5756e-01],
        [-2.9130e-01, -6.1912e-02,  3.3773e-01],
        [ 2.4544e-01, -1.1040e+00,  4.6284e-01],
        [ 7.5777e-01, -4.5980e-01, -6.5317e-01],
        [ 7.0324e-02, -9.6423e-01,  7.0672e-01],
        [ 2.5442e-01, -1.1728e-01, -2.8813e-01],
        [ 8.2889e-02, -6.3136e-01,  3.8429e-01],
        [ 9.3125e-01, -5.5799e-01, -7.6284e-01],
        [ 1.7728e-01, -1.5961e-01, -1.6232e-01],
        [ 4.4376e-01, -5.5514e-01, -1.0193e-01],
        [ 4.5253e-01, -1.7179e+00,  1.0097e+00],
        [-3.2405e-01, -1.2283e+00,  1.5046e+00],
        [-1.5424e-01,  1.5127e+00, -1.0980e+00],
        [-4.5582e-01,  1.0278e+00, -4.2917e-01],
        [-3.4542e-01, -1.2883e+00,  1.6416e+00],
        [ 5.2859e-01, -7.7504e-01, -3.6664e-02],
        [ 4.2904e-01, -1.2302e+00,  5.0293e-01],
        [ 8.1242e-01, -1.5937e+00,  4.3496e-01],
        [ 7.8797e-01, -4.5133e-01, -6.5857e-01],
        [-4.1332e-01,  7.0223e-01, -3.7502e-01],
        [ 1.5428e-01,  9.8868e-02, -3.5167e-01],
        [-9.4999e-02, -2.6184e-01,  2.3495e-01],
        [ 5.9816e-01,  6.6311e-02, -9.3305e-01],
        [-3.6938e-01,  9.9322e-01, -5.9307e-01],
        [ 4.2008e-01, -7.5760e-01,  1.8629e-01],
        [ 3.8300e-01,  7.7358e-01, -1.2207e+00],
        [ 6.2103e-02,  1.1945e-01, -2.7891e-01],
        [-9.5085e-02, -1.1513e-01, -1.6639e-02],
        [-3.1150e-01, -9.2936e-01,  1.1298e+00],
        [ 2.0711e-01,  4.8650e-02, -5.1186e-01],
        [-1.7362e-01,  1.7380e+00, -1.2403e+00],
        [ 6.6880e-01, -1.4634e+00,  4.5136e-01],
        [-1.1879e-01,  8.6680e-01, -7.9610e-01],
        [ 2.6590e-01, -5.6236e-01,  2.2568e-01],
        [ 4.1421e-02, -6.7661e-02, -1.0909e-01],
        [ 8.9838e-02, -2.4718e-01,  2.1901e-02],
        [-6.2250e-02,  4.3071e-01, -4.4755e-01],
        [ 9.1074e-02, -2.9050e-01, -5.7283e-02],
        [ 1.1363e-01, -9.6657e-02, -5.4022e-01],
        [ 1.2962e-01, -3.2556e-01,  5.1235e-03],
        [-1.1471e-01,  1.2516e+00, -8.3134e-01],
        [-6.6803e-01,  1.7878e+00, -5.3210e-01],
        [ 5.8982e-02,  1.2072e-01, -3.8687e-01],
        [-9.0156e-01,  4.9570e-01,  2.7572e-01],
        [ 3.4760e-01, -9.6683e-02, -3.7717e-01],
        [ 3.0015e-01, -1.1367e+00,  5.8159e-01],
        [-9.8886e-03,  2.2212e-01, -2.3561e-01],
        [ 1.9448e-01, -1.4688e-01, -2.2173e-01],
        [ 1.6003e-01,  2.6838e-01, -5.1338e-01],
        [-7.0240e-02, -4.8775e-02, -4.1662e-02],
        [ 1.1453e+00, -7.8535e-01, -8.6296e-01],
        [ 3.6308e-01, -1.3184e+00,  7.2882e-01],
        [ 1.6122e-01, -7.4768e-01,  4.0778e-01],
        [-9.1739e-02, -1.8205e+00,  1.7076e+00],
        [ 4.9205e-01, -4.3471e-01, -3.5623e-01],
        [ 1.8192e-01,  9.4264e-02, -4.3180e-01],
        [-1.0274e-01, -8.8426e-01,  7.9763e-01],
        [ 1.5847e-01,  4.3179e-01, -7.0931e-01],
        [-9.2474e-02, -1.2014e+00,  1.1085e+00],
        [-2.3517e-01,  7.9851e-01, -7.0949e-01],
        [ 3.0216e-01, -2.3666e-01, -2.5625e-01],
        [ 3.8169e-01, -9.4076e-02, -6.1437e-01],
        [-2.0198e-02, -8.6964e-03, -1.0579e-01],
        [-2.2114e-02, -1.7205e+00,  1.5411e+00],
        [-4.2775e-01,  7.7451e-01, -3.4255e-01],
        [ 2.5283e-01, -7.9091e-01,  3.3816e-01],
        [-6.2732e-01, -8.3627e-01,  1.4023e+00],
        [-1.2615e-01,  8.5972e-01, -5.5754e-01],
        [-7.4928e-01,  1.5614e+00, -3.4431e-01],
        [ 8.0641e-03, -1.7628e+00,  1.7750e+00],
        [ 5.6771e-01, -1.3195e+00,  4.4209e-01],
        [ 2.0826e-01, -1.1402e+00,  6.9789e-01],
        [-6.9727e-01,  9.2239e-01, -1.1008e-01],
        [ 4.9960e-01, -1.0178e+00,  2.5666e-01],
        [-2.0830e-01,  9.5879e-01, -7.2576e-01],
        [-7.3961e-01,  1.9217e+00, -7.3419e-01],
        [ 4.5508e-01, -8.0688e-01,  2.4907e-01],
        [ 3.9796e-02,  6.6015e-01, -8.0869e-01],
        [ 9.1451e-02, -1.3206e+00,  1.0454e+00],
        [ 8.2448e-02,  3.8918e-01, -6.9685e-01],
        [-7.6669e-01,  1.7091e+00, -4.6052e-01],
        [-3.2147e-02, -3.8468e-01,  3.5123e-01],
        [ 3.9078e-01, -1.5584e-01, -4.1555e-01],
        [-1.6327e-01,  9.8695e-01, -6.1696e-01],
        [ 4.2952e-01, -3.7832e-01, -1.9976e-01],
        [ 6.5469e-01, -9.4006e-01,  3.6856e-03],
        [-2.8200e-01,  1.2762e+00, -7.0171e-01],
        [-2.0043e-01,  1.0315e+00, -6.8722e-01],
        [ 5.8867e-01, -1.1114e+00,  1.9391e-01],
        [ 4.3161e-02,  2.5245e-01, -4.8522e-01],
        [-1.5615e-01, -1.7370e+00,  1.8268e+00],
        [ 4.7385e-02, -9.0987e-01,  7.3956e-01],
        [ 1.1578e-01,  4.0415e-01, -7.3632e-01],
        [-5.1975e-01, -4.0791e-02,  2.6995e-01],
        [ 4.8962e-01, -1.6692e+00,  8.1582e-01],
        [ 1.6990e-01, -4.4401e-01,  1.2411e-01],
        [ 3.4234e-01,  1.4296e-01, -5.3141e-01],
        [-4.2350e-01,  1.0609e+00, -5.7319e-01],
        [ 5.4790e-01, -7.1733e-01, -2.0764e-01],
        [ 1.8675e-01, -1.8116e-01, -7.8481e-02],
        [ 5.8603e-01, -8.5267e-01, -9.6706e-03],
        [ 2.3783e-01, -1.0241e+00,  5.6610e-01],
        [ 8.2018e-02, -7.0429e-02, -9.7461e-02],
        [-1.2974e-01, -1.8890e+00,  1.8186e+00],
        [-3.5464e-01,  2.0087e+00, -1.2401e+00],
        [ 1.9992e-01, -7.1898e-01,  3.1063e-01],
        [-4.8753e-01,  7.6314e-01, -2.6807e-01],
        [ 2.5854e-01, -2.7974e-01, -2.9291e-01],
        [ 5.5340e-01, -3.4552e-01, -5.3687e-01],
        [-7.4548e-01,  1.7142e+00, -5.5232e-01],
        [ 2.3705e-02, -2.4409e-01,  2.3016e-02],
        [ 2.2639e-01, -1.7241e+00,  1.2776e+00],
        [ 4.7484e-01, -1.2473e+00,  4.2766e-01],
        [ 5.1053e-01, -1.6512e+00,  8.6011e-01],
        [-1.4036e-02,  3.6245e-01, -4.4230e-01],
        [-6.5117e-01,  1.8797e+00, -7.3088e-01],
        [-8.4487e-02,  1.7726e+00, -1.3704e+00],
        [ 1.1982e-01, -1.3752e+00,  1.0401e+00],
        [ 3.1610e-01,  2.6054e-01, -7.9511e-01],
        [ 1.8593e-01, -6.3069e-01,  2.2498e-01],
        [ 2.0648e-01, -3.0070e-01, -1.8244e-01]], device='cuda:0',
       grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [15]:
from sklearn.metrics import classification_report

def evaluate_on_validation(model, tokenizer, df_val):
    # label_2_dict = {'LABEL_0': 'neutral', "LABEL_1" : 'positive', "LABEL_2": 'negative'}
    # classifier = pipeline("text-classification", model= model, tokenizer = tokenizer)
    # answ = classifier.predict(list(df_val["text"]))
    # answ = [label_2_dict[el["label"]] for el in answ]
    label_2_dict = np.array(['neutral', 'positive', 'negative'])
    encoded = tokenizer(list(val_df["text"]), padding=True, truncation=True, max_length=256, return_tensors='pt')
    encoded = {k: v.to(model.device) for k, v in encoded.items()}
    logits = model(**encoded).logits
    preds = label_2_dict[torch.argmax(logits, dim=1).detach().cpu().numpy()]
    
    # print(f1_score(p.label_ids, preds, average='macro'))
    print(classification_report(df_val["labels"], preds))

In [16]:
evaluate_on_validation(model, tokenizer, val_df)

              precision    recall  f1-score   support

    negative       0.60      0.47      0.53        85
     neutral       0.40      0.56      0.47        77
    positive       0.53      0.45      0.49        88

    accuracy                           0.49       250
   macro avg       0.51      0.49      0.49       250
weighted avg       0.51      0.49      0.49       250

# MODEL SCORING
When you make a submit, 
1. Make a Quick Save of the notebook, otherwise we may reject your solution! 
2. Add notebook version to the comment for the submit.

===

При отправке решения:

1. Сделайте Quick Save ноутбука, иначе мы можем отклонить ваше решение!
2. Добавьте версию ноутбука в комментарий к отправке.

In [12]:
import hashlib

def create_submission(model, tokenizer, df_test):
    label_2_dict = {'LABEL_0': 'neutral', "LABEL_1" : 'positive', "LABEL_2": 'negative'}
    classifier = pipeline("text-classification", model= model, tokenizer = tokenizer)
    answ = classifier.predict(list(df_test["text"]))
    answ = [label_2_dict[el["label"]] for el in answ]
    
    df = pd.DataFrame({"labels" : answ, "id": df_test['id']})
    hsh = hashlib.sha256(df.to_csv(index=False).encode('utf-8')).hexdigest()[:8]
    submit_path = f"submit_{hsh}.csv"
    print(f"SUBMIT_NAME: {submit_path}")
    print(df.head(10))
    df.to_csv(submit_path,index=False)

In [ ]:
create_submission(model, tokenizer, test_df)